### ISSUE TITLE
Детектируется как вирус

### ISSUE THREAD

**Issue by UksusoFF** [proDOOMman/SberbankUnroot#1]
До сегодня было все нормально 

![screenshot_20170530-102257](https://cloud.githubusercontent.com/assets/1931442/26570983/6de0e114-4524-11e7-9949-45fb97d906c5.png)

**Comment by proDOOMman** [comment]
Чтобы "антивирус" не ругался достаточно изменить имя пакета и пересобрать модуль. _Делать этого я конечно не буду._
На 4pda уже есть готовый модифицированный apk.

**Comment by UksusoFF** [comment]
> Делать этого я конечно не буду.

Жаль :(
